CREATE DATABASE IF NOT EXISTS people;

use people;

CREATE TABLE IF NOT EXISTS users (
    user_id INT NOT NULL AUTO_INCREMENT, 
    name VARCHAR(155) NOT NULL, 
    PRIMARY KEY(user_id)
);

CREATE TABLE IF NOT EXISTS projects (
    project_id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(155) NOT NULL,
    PRIMARY KEY(project_id)
);

------

CREATE TABLE contest (
   id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE contestant (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    contest_id INT(11) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    points FLOAT(4) NOT NULL,
    inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE judges (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    contest_id INT(11) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)


CREATE TABLE contest_rounds (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    contest_id INT(11) NOT NULL,
    contest_round INT(1) NOT NULL,
    contestant_1 VARCHAR(50) NOT NULL,
    contestant_2 VARCHAR(50) NOT NULL,
    contestant_3 VARCHAR(50) NOT NULL,
    contestant_4 VARCHAR(50) NOT NULL,
    contestant_5 VARCHAR(50) NOT NULL,
    contestant_6 VARCHAR(50) NOT NULL,
    contestant_7 VARCHAR(50) NOT NULL,
    contestant_8 VARCHAR(50) NOT NULL,
    contestant_9 VARCHAR(50) NOT NULL,
    contestant_10 VARCHAR(50) NOT NULL,
    inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)



CREATE TABLE genres (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    genre INT(11) NOT NULL,
    inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)



